### PR TITLE
 Carousel can't work under 768px width #25

### LINKED ISSUE #25: carousel 相關功能在 768px 以下失效
carousel 相關功能在 768px 以下失效

原設計圖 768px 未設計好，
請自行設計提供適當的使用者體驗

或是保留原先切換按鈕調整適合 768px 以下的 size

### PR DESCRIPTION
**Pull request by nstksean**
#25 fix banner problem.

# PR Checklist
- [x]  Tests for the changes have been added (for bug fixes / features)
- [x]  Docs have been added / updated (for bug fixes / features)
PR Type
## What kind of change does this PR introduce?

- [x]  Bugfix
- [x]  Feature

## What is the new behavior?
Fix banner carousel under 768/375px .
Widen slide change button at lest 44px width for UX.

Does this PR introduce a breaking change?

 - [x] Yes
 - [ ] No
Other information：
375px 改善後圖片
截圖 2022-10-25 下午1 28 08

### CODE REVIEW

**Comment by lucifiel0121** [comment]
熱門景點沒有修

**Comment by nstksean** [comment]
## What is the new behavior?
Fix conflict with origin main.
Add a component only can see under 640px screen width. 
Change button position for user experience.
<p align="center">
截圖 2022-10-26 下午10 34 07
<br/><span>375 px.</span>
</p>
<p align="center">
截圖 2022-10-26 下午9 31 42
<br/><span>768 px.</span>
</p>
<p align="center">
截圖 2022-10-26 下午10 06 54 
<br/><span>1440px.</span>
</p>

**Comment by lucifiel0121** [comment]
1. 熱門景點 新增的 btn 位置 375px 很奇怪
2. conflict 解後自己merge

**Comment by nstksean** [comment]
375 px Btn 移動到上面會比較好嗎？
當時的想法是滑到下面了，才會想看其他的部分，所以把東西放下面。

**Pull request merged**
