### PR TITLE
Fix UI for 1440 and 768 pixel width

### PR DESCRIPTION
**Pull request by nstksean**
# PR Checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x]  Docs have been added / updated (for bug fixes / features)
# PR Type
What kind of change does this PR introduce?

- [x]  Bugfix
- [x]  Feature
- [ ]  Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
- [ ]  CI related changes
- [ ]  Documentation content changes
- [ ]  Other... Please describe:
# What is the new behavior?
[5d17412] fix UI 768w
[5e28e4f] fix all UI 1440w

# Does this PR introduce a breaking change?
- [x]  Yes
- [ ] No
# Other information
Photo for result:
1440hp
1440 UI homePage
1440hpfix
1440 UI cover in design
1440gf
1440 人氣美食 UI 補充
768hp
768 UI cover in design

### CODE REVIEW

**Comment by lucifiel0121** [comment]
人氣美食區塊 沒有 img 不符合設計

**Comment by nstksean** [comment]
人氣美食區的圖片可否做在另一個ＰＲ中？

**Comment by lucifiel0121** [comment]
ＵＩ需求就是有這個功能 沒理由另一個ＰＲ中
不然就你做另一個ＰＲ自行 merge 進這個分支
最終我檢查就是要ＵＩ完備

這功能沒有很難 我想不到任何理由要分開做

**Comment by nstksean** [comment]
收到，馬上處理。

**Comment by lucifiel0121** [comment]
跑版
截圖 2022-10-13 下午9 00 48
截圖 2022-10-13 下午9 00 19

**Comment by nstksean** [comment]
Test in 2500px width.
截圖 2022-10-13 下午9 23 11
截圖 2022-10-13 下午9 23 21

**Pull request merged**
